name: "Update Github Status"
description: "Updates a status via the Github Statuses API"
inputs:
  context:
    description: A string label to differentiate this status from the status of other systems.
    required: true
  description:
    description: A short description of the status.
    required: false
  repository:
    description: The repository to update.
    required: false
    default: ${{ github.repository }}
  sha:
    description: The SHA to associate with the status.
    required: true
    default: ${{ github.sha }}
  state:
    description: The state of the system.
    required: true
    default: "pending"
  target_url:
    description: The target URL to associate with this status.
    required: false
  token:
    description: "A personal access token to override Github's default token"
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: update status
      shell: bash
      run: |
        curl \
          --request POST \
          --header "Authorization: bearer ${{ inputs.token }}" \
          --header "Accept: application/vnd.github.v3+json" \
          --url "https://api.github.com/repos/${{ inputs.repository }}/statuses/${{ inputs.sha }}" \
          --data-binary @- << EOF
            {
              "context": "${{ inputs.context }}",
              "description": "${{ inputs.description }}",
              "state": "${{ inputs.state }}",
              "target_url": "${{ inputs.target_url }}"
            }
        EOF
